version: '3'
services:
  frontend:
    build:
      context: ./pruebaCrudFront
    ports:
      - "5174:80"
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build:
      context: ./PruebaCrud
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
